services:
  postgres:
    image: postgres:17.0-alpine3.20
    container_name: xpay_postgres
    environment:
      POSTGRES_DB: xpay
      POSTGRES_USER: ash
      POSTGRES_PASSWORD: samplepass
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ash -d xpay"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - xpay_network

volumes:
  pg_data:
    name: xpay_pg_data

networks:
  xpay_network:
    name: xpay_network
    driver: bridge
